# All data in this file are generated by main.py
import numpy as np
import matplotlib.pyplot as plt

parameters = np.array(['[8,10,5]', '[6,7,4]', '[5,5,4]', '[6,7,3]', '[5,5,3]'])
MC_win_rate = np.array([0.99, 1, 0.99, 0.99, 0.98])
MC_efficiency = np.array([7480419, 2693262, 2013351, 1227358, 835892])
CNN_win_rate = np.array([1, 0.99, 0.97, 0.98, 0.98])
CNN_efficiency = np.array([88352, 28768, 15670, 13972, 8008])

plt.figure()
plt.subplot(2,2,1)
plt.bar(range(5),MC_win_rate)
plt.xticks(range(5), parameters)
plt.title('Monte Carlo win rate')

plt.subplot(2,2,2)
plt.bar(range(5),CNN_win_rate)
plt.xticks(range(5), parameters)
plt.title('CNN win rate')

plt.subplot(2,2,3)
plt.bar(range(5),MC_efficiency)
plt.xticks(range(5), parameters)
plt.title('Monte Carlo efficiency')

plt.subplot(2,2,4)
plt.bar(range(5),CNN_efficiency)
plt.xticks(range(5), parameters)
plt.title('CNN efficiency')

plt.show()